package com.tgj.entity;
// default package
// Generated 2018-5-22 14:40:26 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Classify generated by hbm2java
 */
@JsonIgnoreProperties(value = {"models", "handler", "hibernateLazyInitializer"})
@Entity
@Table(name = "d_classify", catalog = "rykj", uniqueConstraints = @UniqueConstraint(columnNames = "d_no"))
public class Classify implements java.io.Serializable {

	private static final long serialVersionUID = -4676776569207528511L;
	private Integer id;
	private String name;
	private String no;
	private String description;
	private Project project;
	private Set<Model> models = new HashSet<>();

	public Classify() {
	}

	public Classify(String name, String no) {
		this.name = name;
		this.no = no;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "d_id", unique = true, nullable = false, updatable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "d_name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "d_no", unique = true, nullable = false, length = 4)
	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	@Column(name = "d_description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Override
	public String toString() {
		return "Classify [id=" + id + ", name=" + name + ", no=" + no + ", description=" + description + ", projectId="
				+ project + "]";
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classify")
	public Set<Model> getModels() {
		return models;
	}

	public void setModels(Set<Model> models) {
		this.models = models;
	}
	
	

}
