package com.tgj.entity;
// default package
// Generated 2018-5-22 14:40:26 by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name = "d_function", catalog = "rykj")
public class Function implements java.io.Serializable {

	private static final long serialVersionUID = -1036178565201656577L;
	private Integer id;
	private String no;
	private String name;
	private String description;
	private Model model;
	private Float fromPrice;
	private Float toPrice;
	

	public Function() {
	}

	public Function(String no, String name) {
		this.no = no;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "d_id", unique = true, nullable = false, updatable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "d_no", nullable = false, length = 7)
	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	@Column(name = "d_name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "d_description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	public Model getModel() {
		return this.model;
	}

	public void setModel(Model model) {
		this.model = model;
	}
	
	@Column(name = "d_from_price")
	public Float getFromPrice() {
		return fromPrice;
	}

	public void setFromPrice(Float fromPrice) {
		this.fromPrice = fromPrice;
	}

	@Column(name = "d_to_price")
	public Float getToPrice() {
		return toPrice;
	}

	public void setToPrice(Float toPrice) {
		this.toPrice = toPrice;
	}

	@Override
	public String toString() {
		return "Function [id=" + id + ", no=" + no + ", name=" + name + ", description=" + description + "]";
	}
	
	

}
